dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: opendj4
  version: 0.3.0
  repository: https://raw.githubusercontent.com/joostvdg/helm-repo/master/
  alias: ldap
